default: &default
  adapter: postgis
  encoding: unicode
  postgis_extension: postgis      # default is postgis
  postgis_schema: public          # default is public
  schema_search_path: public,postgis
  pool: 5
  username: steve
  password:
  su_username: steve
  su_password:

development:
  <<: *default
  database: journey_dev

test:
  <<: *default
  database: journey_test
