# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5cf5b7ac9a900a72e2a88c3a02344185c9909cdc7a1de3600ee20ce8859c99cee92aad3f1f63381eb06c69a50cfe9164bd35b3b53b33dc97025e7a6290e9b6d7

test:
  secret_key_base: 80d17622dfae7168e7e8304646bd139e7b2be6e43b2a9cc391423767c917dd3f48197ffc9348f1158b6ae6f9eabee2645f1c5003e15a149f6b85bd484742d57c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
